In [42]:
import os
os.chdir("/home/raymo/zeek_lab")
os.getcwd()


path = "data/analysis/conn_analysis.json"

with open(path) as f:
    results = json.load(f)

results

{'top_talkers': {'192.168.1.177': 547},
 'top_destinations': {'204.74.99.103': 63,
  '23.36.21.174': 16,
  '72.153.5.137': 14,
  '162.247.243.29': 13,
  '23.44.73.178': 13,
  '34.96.127.16': 9,
  '172.184.91.15': 8,
  '51.8.71.184': 7,
  '44.199.181.222': 7,
  '142.251.46.229': 7,
  '18.206.37.118': 6,
  '44.199.181.5': 6,
  '44.215.118.141': 6,
  '52.27.100.156': 5,
  '142.251.214.133': 5,
  '44.215.133.88': 5,
  '52.123.129.14': 5,
  '23.67.33.148': 5,
  '151.101.201.16': 5,
  '150.171.27.11': 4},
 'port_distribution': {'443': 522, '80': 24, '5228': 1},
 'conn_states': {'SF': 424,
  'REJ': 62,
  'RSTR': 23,
  'RSTO': 16,
  'S1': 12,
  'OTH': 6,
  'RSTRH': 2,
  'SH': 2},
 'elephant_flows': [{'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.184.91.15',
   'id.resp_p': 80,
   'total_bytes': 27299708},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.184.91.15',
   'id.resp_p': 80,
   'total_bytes': 25202470},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '23.67.33.137',
   'id.resp_p': 443,
   'total_bytes': 19041223},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '151.101.202.172',
   'id.resp_p': 80,
   'total_bytes': 6702366},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '151.101.202.172',
   'id.resp_p': 80,
   'total_bytes': 2395040},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.184.91.15',
   'id.resp_p': 80,
   'total_bytes': 1051375},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.184.91.15',
   'id.resp_p': 80,
   'total_bytes': 1051360},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.184.91.15',
   'id.resp_p': 80,
   'total_bytes': 1051356},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '23.67.33.148',
   'id.resp_p': 80,
   'total_bytes': 977975},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '23.67.33.148',
   'id.resp_p': 80,
   'total_bytes': 853785},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '23.216.149.141',
   'id.resp_p': 443,
   'total_bytes': 773628},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '100.21.175.239',
   'id.resp_p': 443,
   'total_bytes': 531918},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '142.250.189.174',
   'id.resp_p': 443,
   'total_bytes': 418749},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '52.137.106.217',
   'id.resp_p': 443,
   'total_bytes': 402011},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '44.215.118.141',
   'id.resp_p': 443,
   'total_bytes': 286393},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '23.67.33.148',
   'id.resp_p': 443,
   'total_bytes': 241967},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '23.67.33.148',
   'id.resp_p': 80,
   'total_bytes': 231135},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.184.91.15',
   'id.resp_p': 80,
   'total_bytes': 210854},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '104.18.41.41',
   'id.resp_p': 443,
   'total_bytes': 207037},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '142.251.46.229',
   'id.resp_p': 443,
   'total_bytes': 166429}],
 'long_lived': [{'id.orig_h': '192.168.1.177',
   'id.resp_h': '142.250.142.188',
   'id.resp_p': 5228,
   'duration': 6121.331722},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '20.59.87.225',
   'id.resp_p': 443,
   'duration': 5906.183613},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '104.18.39.21',
   'id.resp_p': 443,
   'duration': 1909.927018},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.64.148.235',
   'id.resp_p': 443,
   'duration': 1850.236293},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '34.96.127.16',
   'id.resp_p': 443,
   'duration': 1773.656926},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '98.84.223.133',
   'id.resp_p': 443,
   'duration': 1756.724373},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '162.247.241.14',
   'id.resp_p': 443,
   'duration': 1756.617465},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '3.226.61.205',
   'id.resp_p': 443,
   'duration': 1756.403834},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '172.64.148.235',
   'id.resp_p': 443,
   'duration': 1750.781277},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '34.96.127.16',
   'id.resp_p': 443,
   'duration': 1721.595163},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '34.104.128.0',
   'id.resp_p': 443,
   'duration': 1524.282936},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '34.104.128.0',
   'id.resp_p': 443,
   'duration': 1492.450388},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '162.247.243.29',
   'id.resp_p': 443,
   'duration': 1276.65231},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '162.247.243.29',
   'id.resp_p': 443,
   'duration': 1140.183648},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '52.44.77.10',
   'id.resp_p': 443,
   'duration': 1140.096861},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '34.96.127.16',
   'id.resp_p': 443,
   'duration': 887.601532},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '34.96.127.16',
   'id.resp_p': 443,
   'duration': 874.067607},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '104.18.41.41',
   'id.resp_p': 443,
   'duration': 820.093564},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '3.217.30.234',
   'id.resp_p': 443,
   'duration': 678.678428},
  {'id.orig_h': '192.168.1.177',
   'id.resp_h': '35.241.15.198',
   'id.resp_p': 443,
   'duration': 672.157934}]}

In [43]:
df_top_talkers = pd.DataFrame(
    results["top_talkers"].items(),
    columns=["Host", "Count"]
).sort_values("Count", ascending=False)

df_top_talkers

            Host  Count
0  192.168.1.177    547

In [44]:
df_top_destinations = pd.DataFrame(
    results["top_destinations"].items(),
    columns=["Destination", "Count"]
).sort_values("Count", ascending=False)

df_top_destinations

        Destination  Count
0     204.74.99.103     63
1      23.36.21.174     16
2      72.153.5.137     14
3    162.247.243.29     13
4      23.44.73.178     13
5      34.96.127.16      9
6     172.184.91.15      8
7       51.8.71.184      7
8    44.199.181.222      7
9    142.251.46.229      7
10    18.206.37.118      6
11     44.199.181.5      6
12   44.215.118.141      6
13    52.27.100.156      5
14  142.251.214.133      5
15    44.215.133.88      5
16    52.123.129.14      5
17     23.67.33.148      5
18   151.101.201.16      5
19    150.171.27.11      4

In [45]:
df_port_distribution = pd.DataFrame(
    results["port_distribution"].items(),
    columns=["Port", "Count"]
).sort_values("Count", ascending=False)

df_port_distribution

   Port  Count
0   443    522
1    80     24
2  5228      1

In [46]:
df_conn_states = pd.DataFrame(
    results["conn_states"].items(),
    columns=["State", "Count"]
).sort_values("Count", ascending=False)

df_conn_states

   State  Count
0     SF    424
1    REJ     62
2   RSTR     23
3   RSTO     16
4     S1     12
5    OTH      6
6  RSTRH      2
7     SH      2

In [47]:
df_elephant_flows = pd.DataFrame(results["elephant_flows"])
df_elephant_flows

        id.orig_h        id.resp_h  id.resp_p  total_bytes
0   192.168.1.177    172.184.91.15         80     27299708
1   192.168.1.177    172.184.91.15         80     25202470
2   192.168.1.177     23.67.33.137        443     19041223
3   192.168.1.177  151.101.202.172         80      6702366
4   192.168.1.177  151.101.202.172         80      2395040
5   192.168.1.177    172.184.91.15         80      1051375
6   192.168.1.177    172.184.91.15         80      1051360
7   192.168.1.177    172.184.91.15         80      1051356
8   192.168.1.177     23.67.33.148         80       977975
9   192.168.1.177     23.67.33.148         80       853785
10  192.168.1.177   23.216.149.141        443       773628
11  192.168.1.177   100.21.175.239        443       531918
12  192.168.1.177  142.250.189.174        443       418749
13  192.168.1.177   52.137.106.217        443       402011
14  192.168.1.177   44.215.118.141        443       286393
15  192.168.1.177     23.67.33.148        443       241967
16  192.168.1.177     23.67.33.148         80       231135
17  192.168.1.177    172.184.91.15         80       210854
18  192.168.1.177     104.18.41.41        443       207037
19  192.168.1.177   142.251.46.229        443       166429

In [48]:
df_long_lived = pd.DataFrame(results["long_lived"])
df_long_lived

        id.orig_h        id.resp_h  id.resp_p     duration
0   192.168.1.177  142.250.142.188       5228  6121.331722
1   192.168.1.177     20.59.87.225        443  5906.183613
2   192.168.1.177     104.18.39.21        443  1909.927018
3   192.168.1.177   172.64.148.235        443  1850.236293
4   192.168.1.177     34.96.127.16        443  1773.656926
5   192.168.1.177    98.84.223.133        443  1756.724373
6   192.168.1.177   162.247.241.14        443  1756.617465
7   192.168.1.177     3.226.61.205        443  1756.403834
8   192.168.1.177   172.64.148.235        443  1750.781277
9   192.168.1.177     34.96.127.16        443  1721.595163
10  192.168.1.177     34.104.128.0        443  1524.282936
11  192.168.1.177     34.104.128.0        443  1492.450388
12  192.168.1.177   162.247.243.29        443  1276.652310
13  192.168.1.177   162.247.243.29        443  1140.183648
14  192.168.1.177      52.44.77.10        443  1140.096861
15  192.168.1.177     34.96.127.16        443   887.601532
16  192.168.1.177     34.96.127.16        443   874.067607
17  192.168.1.177     104.18.41.41        443   820.093564
18  192.168.1.177     3.217.30.234        443   678.678428
19  192.168.1.177    35.241.15.198        443   672.157934

In [49]:
df_top_pairs = pd.DataFrame(results.get("top_pairs", []))
df_top_pairs

Empty DataFrame
Columns: []
Index: []

In [50]:
import pandas as pd
pd.json_normalize(results, sep="_")

,elephant_flows,long_lived,top_talkers_192.168.1.177,top_destinations_204.74.99.103,top_destinations_23.36.21.174,top_destinations_72.153.5.137,top_destinations_162.247.243.29,top_destinations_23.44.73.178,top_destinations_34.96.127.16,top_destinations_172.184.91.15,...,port_distribution_80,port_distribution_5228,conn_states_SF,conn_states_REJ,conn_states_RSTR,conn_states_RSTO,conn_states_S1,conn_states_OTH,conn_states_RSTRH,conn_states_SH
0,"[{'id.orig_h': '192.168.1.177', 'id.resp_h': '...","[{'id.orig_h': '192.168.1.177', 'id.resp_h': '...",547,63,16,14,13,13,9,8,...,24,1,424,62,23,16,12,6,2,2

In [51]:
import pandas as pd
from io import StringIO

def load_conn_log(path):
    with open(path, "r") as f:
        lines = f.readlines()

    header = None
    for line in lines:
        if line.startswith("#fields"):
            header = line.strip().split()[1:]
            break

    data = [l for l in lines if not l.startswith("#")]

    return pd.read_csv(
        StringIO("".join(data)),
        sep="\t",
        names=header,
        engine="python"
    )

df = load_conn_log("logs/logs_reval-cap/conn.log")
df.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,1.759356e+09,C6Xz8u11Em3PnMTb7b,192.168.1.177,50258,52.39.112.131,443,tcp,-,1.246052,0,...,T,F,0,^dfAFRa,3,120,3,144,-,6
1,1.759356e+09,CnJaHG3pVdbQFxCOEi,192.168.1.177,50303,142.251.46.174,443,tcp,ssl,0.071970,1810,...,T,F,0,ShADadFRf,8,2142,12,9392,-,6
2,1.759356e+09,CsWlzM21b1BbHliurd,192.168.1.177,52055,192.168.1.1,53,udp,dns,0.014221,38,...,T,T,0,Dd,1,66,1,153,-,17
3,1.759356e+09,CqxGnp39Kv3kFrYXK3,192.168.1.177,63332,192.168.1.1,53,udp,dns,0.015792,38,...,T,T,0,Dd,1,66,1,124,-,17
4,1.759356e+09,CHjEyF2I7S6ZysQnA,192.168.1.177,50305,204.74.99.103,443,tcp,-,0.074389,0,...,T,F,0,Sr,1,52,1,40,-,6

In [52]:
hist = df[df["history"].notna()].copy()
hist.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,1.759356e+09,C6Xz8u11Em3PnMTb7b,192.168.1.177,50258,52.39.112.131,443,tcp,-,1.246052,0,...,T,F,0,^dfAFRa,3,120,3,144,-,6
1,1.759356e+09,CnJaHG3pVdbQFxCOEi,192.168.1.177,50303,142.251.46.174,443,tcp,ssl,0.071970,1810,...,T,F,0,ShADadFRf,8,2142,12,9392,-,6
2,1.759356e+09,CsWlzM21b1BbHliurd,192.168.1.177,52055,192.168.1.1,53,udp,dns,0.014221,38,...,T,T,0,Dd,1,66,1,153,-,17
3,1.759356e+09,CqxGnp39Kv3kFrYXK3,192.168.1.177,63332,192.168.1.1,53,udp,dns,0.015792,38,...,T,T,0,Dd,1,66,1,124,-,17
4,1.759356e+09,CHjEyF2I7S6ZysQnA,192.168.1.177,50305,204.74.99.103,443,tcp,-,0.074389,0,...,T,F,0,Sr,1,52,1,40,-,6

In [53]:
from collections import Counter

all_codes = Counter("".join(hist["history"].tolist()))
df_hist_freq = pd.DataFrame(all_codes.items(), columns=["Code", "Count"]).sort_values("Count", ascending=False)
df_hist_freq

   Code  Count
9     D   3974
1     d   3630
7     S    510
3     A    467
6     a    454
8     h    448
4     F    433
2     f    425
13    T    301
12    -    242
5     R    182
11    t     96
10    r     87
0     ^      4
14    W      4

In [54]:
import pandas as pd
from collections import Counter

# Extract only rows that contain history codes
hist = df[df["history"].notna()].copy()

# Count individual history characters across all rows
all_codes = Counter("".join(hist["history"].tolist()))

# Convert to DataFrame for clean Jupyter display
df_hist_freq = (
    pd.DataFrame(all_codes.items(), columns=["Code", "Count"])
      .sort_values("Count", ascending=False)
      .reset_index(drop=True)
)

df_hist_freq

   Code  Count
0     D   3974
1     d   3630
2     S    510
3     A    467
4     a    454
5     h    448
6     F    433
7     f    425
8     T    301
9     -    242
10    R    182
11    t     96
12    r     87
13    ^      4
14    W      4