In [10]:
import pandas as pd

df = pd.read_json("dns.json", lines=True)
df.shape
df.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,trans_id,rtt,query,...,rcode,rcode_name,AA,TC,RD,RA,Z,answers,TTLs,rejected
0,1.755686e+09,C4Nqx8RC75wB6nh1k,192.168.56.101,53012,8.8.8.8,53,udp,47945,0.035759,apples.ctf.local,...,0,NOERROR,F,F,T,T,0,TXT 28 TFNDVEZ7RE5TX0VYRklMX0ZVTn0=,120.000000,F
1,1.755686e+09,Co1GZ222VpxuITNEll,192.168.56.101,53000,8.8.8.8,53,udp,60399,-,www.google.com,...,-,-,F,F,T,F,0,-,-,F
2,1.755686e+09,CBCbLr3PFO2iYRMDi4,192.168.56.101,53001,8.8.8.8,53,udp,17667,-,example.com,...,-,-,F,F,T,F,0,-,-,F
3,1.755686e+09,Cvbqau2sDQi0gXo0rb,192.168.56.101,53002,8.8.8.8,53,udp,61514,-,www.facebook.com,...,-,-,F,F,T,F,0,-,-,F
4,1.755686e+09,CDQsG53bbEr5F1supl,192.168.56.101,53003,8.8.8.8,53,udp,45594,-,api.github.com,...,-,-,F,F,T,F,0,-,-,F

In [15]:
df.columns
df[['rcode', 'rcode_name']]

   rcode rcode_name
0      0    NOERROR
1      -          -
2      -          -
3      -          -
4      -          -
5      -          -
6      -          -
7      -          -
8      -          -
9      -          -
10     -          -
11     -          -
12     -          -

In [16]:
#%cd ~/zeek_lab/scripts
## Filter DNS Events by UID
import pandas as pd

df = pd.read_json("dns.json", lines=True)

# Safety check
if 'uid' not in df.columns:
    raise KeyError("Column 'uid' not found in DataFrame.")

# Filter rows where uid does NOT contain '-'
filtered = df[~df['uid'].str.contains('-', na=False)]

filtered

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,trans_id,rtt,query,...,rcode,rcode_name,AA,TC,RD,RA,Z,answers,TTLs,rejected
0,1.755686e+09,C4Nqx8RC75wB6nh1k,192.168.56.101,53012,8.8.8.8,53,udp,47945,0.035759,apples.ctf.local,...,0,NOERROR,F,F,T,T,0,TXT 28 TFNDVEZ7RE5TX0VYRklMX0ZVTn0=,120.000000,F
1,1.755686e+09,Co1GZ222VpxuITNEll,192.168.56.101,53000,8.8.8.8,53,udp,60399,-,www.google.com,...,-,-,F,F,T,F,0,-,-,F
2,1.755686e+09,CBCbLr3PFO2iYRMDi4,192.168.56.101,53001,8.8.8.8,53,udp,17667,-,example.com,...,-,-,F,F,T,F,0,-,-,F
3,1.755686e+09,Cvbqau2sDQi0gXo0rb,192.168.56.101,53002,8.8.8.8,53,udp,61514,-,www.facebook.com,...,-,-,F,F,T,F,0,-,-,F
4,1.755686e+09,CDQsG53bbEr5F1supl,192.168.56.101,53003,8.8.8.8,53,udp,45594,-,api.github.com,...,-,-,F,F,T,F,0,-,-,F
5,1.755686e+09,CdoBpE1ziA4W8MLmng,192.168.56.101,53004,8.8.8.8,53,udp,37112,-,docs.python.org,...,-,-,F,F,T,F,0,-,-,F
6,1.755686e+09,C4OsDR1eqvCQqtOJ69,192.168.56.101,53005,8.8.8.8,53,udp,61162,-,news.ycombinator.com,...,-,-,F,F,T,F,0,-,-,F
7,1.755686e+09,CoRUo928WR5S4b520c,192.168.56.101,53006,8.8.8.8,53,udp,32251,-,login.microsoftonline.com,...,-,-,F,F,T,F,0,-,-,F
8,1.755686e+09,CYEmCY3jPOMJmiH3si,192.168.56.101,53007,8.8.8.8,53,udp,18801,-,cdn.jsdelivr.net,...,-,-,F,F,T,F,0,-,-,F
9,1.755686e+09,CnHPta3UcSDb5iKKzc,192.168.56.101,53008,8.8.8.8,53,udp,36901,-,pypi.org,...,-,-,F,F,T,F,0,-,-,F
10,1.755686e+09,C9LDjM1H2Nq4O9Qslf,192.168.56.101,53009,8.8.8.8,53,udp,1674,-,content.delivery.net,...,-,-,F,F,T,F,0,-,-,F
11,1.755686e+09,C53KmvF94wUIeGLn1,192.168.56.101,53010,8.8.8.8,53,udp,15451,-,red.herring.ctf.local,...,-,-,F,F,T,F,0,-,-,F
12,1.755686e+09,CmMqF83sFIAfiViOl3,192.168.56.101,53011,8.8.8.8,53,udp,30091,-,totally-normal.example.net,...,-,-,F,F,T,F,0,-,-,F